import type { Metadata } from "next";
import "./globals.css";
import ClientRootLayout from "./client-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="m-0 p-0">
      <body className="antialiased m-0 p-0">
        <ClientRootLayout>{children}</ClientRootLayout>
      </body>
    </html>
  );
}
